version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "US/Pacific"
