name: Publish Nuget Package
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-nuget-package:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Auth to github nuget feed.
        shell: pwsh
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DarkgreyDevelopment/index.json"

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Build and Pack library
        shell: pwsh
        run: |
          Set-Location './src'
          dotnet build -c Release
          dotnet pack -c Release

      - name: Publish library to github nuget Feed.
        shell: pwsh
        run: |
          Set-Location 'src/bin/Release/'
          dotnet nuget push (Get-Item -Path 'Werkr.Common.*.nupkg').Name --source "github" --skip-duplicate
